#!/bin/bash

# Convert the binary number stored in the BINARY environment variable to base 10 using the arithmetic expansion
decimal_number=$((2#$BINARY))

# Display the number in base 10 followed by a new line
echo $decimal_number


